import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function boot(){
 const els=new Map(),events={},frames=[],orient={matches:false,listeners:{},addEventListener(k,f){this.listeners[k]=f;}};
 const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,p)=>p in o?o[p]:()=>{}});
 class Element{
 constructor(){this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';this.style={setProperty(){}};this.dataset={};this.attrs={};this.children=[];this.listeners={};this.classes=new Set();this.classList={add:v=>this.classes.add(v),remove:v=>this.classes.delete(v),toggle:(v,b)=>b?this.classes.add(v):this.classes.delete(v)};this.width=1080;this.height=560;this.nodes={};}
 setAttribute(k,v){this.attrs[k]=v;}append(el){this.children.push(el);}querySelector(s){return this.nodes[s]||(this.nodes[s]=new Element());}getContext(){return ctx;}getBoundingClientRect(){return {left:0,top:0,width:1080,height:560};}addEventListener(k,f){this.listeners[k]=f;}click(){return this.onclick?.({preventDefault(){}});}
 }
 const document={hidden:false,getElementById:id=>{if(!els.has(id))els.set(id,new Element());return els.get(id);},createElement:()=>new Element(),querySelector:()=>document.getElementById('wordmark'),addEventListener:(k,f)=>events[k]=f};
 for(const id of ['pause-menu','result','guide','install','boss-bar','banner'])document.getElementById(id).hidden=true;
 const storage={};let now=1;
 const sandbox={console,document,navigator:{},window:{devicePixelRatio:1,addEventListener:(k,f)=>events[k]=f},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},performance:{now:()=>now},matchMedia:()=>orient,ResizeObserver:class{observe(){}},Image:class{set src(v){queueMicrotask(()=>this.onload?.());}},requestAnimationFrame:f=>frames.push(f),Promise,Math,queueMicrotask};
 const context=vm.createContext(sandbox);const root=new URL('../',import.meta.url);let source='';for(const name of ['config','engine','art','renderer','audio','app'])source+=fs.readFileSync(new URL('src/'+name+'.js',root),'utf8').replace(/^import .*?;\s*$/gm,'').replace(/export /g,'')+'\n';
 vm.runInContext(source,context);return {els,events,orient,context,document,frame:dt=>{now+=dt*1000;const f=frames.shift();f?.(now);},get:code=>vm.runInContext(code,context)};
}
async function ready(){const h=boot();await new Promise(resolve=>setImmediate(resolve));return h;}
test('application boots, portraits preload, and five touch cards are available',async()=>{const h=await ready();assert.equal(h.els.get('start').disabled,false);assert.equal(h.els.get('cards').children.length,5);assert.equal(h.get('ready'),true);h.frame(.016);});
test('touch places the guided units with accurate world-coordinate mapping',async()=>{const h=await ready();await h.els.get('start').click();const canvas=h.els.get('game');const tap=(x,y)=>canvas.listeners.pointerdown({preventDefault(){},clientX:x,clientY:y});tap(162,90);assert.equal(h.get('game.pugs[0].type'),'chef');assert.equal(h.get('selected'),'bark');tap(362,90);assert.equal(h.get('game.tutorial'),2);assert.equal(h.get('game.pugs.length'),2);assert.equal(h.get('selected'),null);assert.equal(h.els.get('menu').hidden,true);});
test('backgrounding, orientation changes and explicit resume preserve the level',async()=>{const h=await ready();await h.els.get('start').click();h.get("game.tutorial=2;game.update(.05)");const before=h.get('game.time');h.document.hidden=true;h.events.visibilitychange();assert.equal(h.get('game.status'),'paused');for(let i=0;i<10;i++)h.frame(10);assert.equal(h.get('game.time'),before);h.document.hidden=false;await h.els.get('resume').click();assert.equal(h.get('game.status'),'playing');h.orient.matches=true;h.orient.listeners.change();assert.equal(h.get('game.status'),'paused');await h.els.get('resume').click();assert.equal(h.get('game.status'),'paused');h.orient.matches=false;h.orient.listeners.change();await h.els.get('resume').click();assert.equal(h.get('game.status'),'playing');});
test('guide pauses gameplay, closes into the previous state, and restart clears selections',async()=>{const h=await ready();await h.els.get('start').click();h.els.get('help').click();assert.equal(h.get('game.status'),'paused');assert.equal(h.els.get('guide').hidden,false);await h.els.get('close-guide').click();assert.equal(h.get('game.status'),'playing');h.els.get('pause').click();assert.equal(h.els.get('pause-menu').hidden,false);await h.els.get('restart-pause').click();assert.equal(h.get('game.time'),0);assert.equal(h.get('selected'),'chef');assert.equal(h.els.get('pause-menu').hidden,true);});
test('victory and defeat show their result screens, then restart',async()=>{for(const outcome of ['won','lost']){const h=await ready();await h.els.get('start').click();h.get(`game.finish('${outcome}')`);assert.equal(h.els.get('result').hidden,false);assert.ok(h.els.get('result-title').textContent.length>0);await h.els.get('restart-result').click();assert.equal(h.els.get('result').hidden,true);assert.equal(h.get('game.status'),'playing');}});
